ALTER TABLE bosslog_daily
    MODIFY COLUMN `bosstype` ENUM ('ZAKUM','CHAOS_ZAKUM','HORNTAIL','CHAOS_HORNTAIL','PINKBEAN','SCARGA','PAPULATUS') NOT NULL;

ALTER TABLE bosslog_weekly
    MODIFY COLUMN `bosstype` ENUM ('ZAKUM','CHAOS_ZAKUM','HORNTAIL','CHAOS_HORNTAIL','PINKBEAN','SCARGA','PAPULATUS') NOT NULL;
