package soloMapling.ArtificialPlayer.GCMoveSystem;

import java.awt.Point;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ThreadLocalRandom;
import org.gms.client.Character;
import org.gms.server.maps.Foothold;
import org.gms.server.maps.Rope;
import soloMapling.ArtificialPlayer.GCMoveSystem.BotNavigationGraph;

/* loaded from: asm-bot-mini.jar:org/gms/soloMapling/ArtificialPlayer/GCMoveSystem/BotMovementState.class */
class BotMovementState {
    final Character bot;
    volatile Character owner;
    ScheduledFuture<?> task;
    volatile boolean following = false;
    volatile int followTargetId = 0;
    BotMovementProfile movementProfile = BotMovementProfile.base();
    long lastProfileRefreshMs = 0;
    float velY = 0.0f;
    double hspeed = 0.0d;
    double physX = 0.0d;
    double physY = 0.0d;
    double groundPhysicsCarryMs = 0.0d;
    double fallPeakPhysY = Double.POSITIVE_INFINITY;
    boolean inAir = false;
    int jumpCooldownMs = 0;
    int movementVelX = 0;
    int movementVelY = 0;
    int facingDir = 1;
    boolean crouching = false;
    boolean swimming = false;
    int swimMoveDir = 0;
    int swimVerticalHold = 0;
    boolean swimJumpRequested = false;
    long swimNextJumpAtMs = 0;
    int moveDir = 0;
    int groundBrakeDir = 0;
    boolean climbing = false;
    Rope climbRope = null;
    Rope blockedRopeGrab = null;
    int climbVerticalDir = 0;
    boolean wasMovingX = false;
    int airVelX = 0;
    double airSteerVelX = 0.0d;
    boolean fixedAirArc = false;
    boolean pendingFlashJump = false;
    boolean flashJumpFired = false;
    float flashJumpScale = 1.0f;
    boolean climbUpIntent = false;
    int ropeGrabCooldownMs = 0;
    boolean downJumpPending = false;
    long downJumpGracePeriodMS = 0;
    boolean ropeEntryPending = false;
    Rope ropeEntryRope = null;
    int ropeEntryY = 0;
    volatile boolean grinding = false;
    volatile boolean resting = false;
    int attackCooldownMs = 0;
    volatile boolean shopVisitPending = false;
    int followTravelTargetMapId = -1;
    long portalUseCooldownUntilMs = 0;
    int portalEnterReadyTicks = -1;
    long alertedUntilMs = 0;
    boolean alertResetScheduled = false;
    int mobHitCooldownMs = 0;
    Point lastMobTouchCheckPos = null;
    int lastMobTouchMapId = -1;
    int lastMapId = -1;
    Map<Integer, Foothold> fhIndex = new HashMap();
    int followOffsetX = 0;
    int skipDelayMs = ThreadLocalRandom.current().nextInt(0, 501);
    int spawnWarmupMs = 2000 + ThreadLocalRandom.current().nextInt(0, 5001);
    int aiTickAccumulatorMs = 0;
    volatile boolean tickStopped = false;
    MovementPlan coarsePlan = null;
    long coarsePlanStartMs = 0;
    Point coarsePlanTarget = null;
    int coarsePlanMapId = -1;
    boolean coarseActive = false;
    long portalDropAtMs = 0;
    long duckUntilMs = 0;
    long reactingUntilMs = 0;
    long nextPlayerScanMs = 0;
    Point moveTarget = null;
    boolean moveTargetPrecise = false;
    String moveTargetSource = null;
    int moveBestDist = Integer.MAX_VALUE;
    long moveProgressAtMs = 0;
    Point farmAnchor = null;
    int farmAnchorMapId = -1;
    String lastEdgeBlockReason = null;
    Point navTargetPos = null;
    BotNavigationGraph navGraph = null;
    BotNavigationGraph.Edge navEdge = null;
    BotNavigationGraph.Edge navJumpLaunchEdge = null;
    int navJumpLaunchX = Integer.MIN_VALUE;
    int navJumpLaunchDelaySteps = Integer.MIN_VALUE;
    int navTargetRegionId = -1;
    boolean navPreciseTarget = false;
    int navBlockedPosTicks = 0;
    int navBlockedPosGiveUpTicks = 0;
    int navBlockedPosX = Integer.MIN_VALUE;
    int navBlockedPosY = Integer.MIN_VALUE;
    boolean graphWarmupFallback = false;
    int observedOwnerStepX = 0;
    int observedOwnerStepY = 0;
    String lastNavDecision = "-";
    int stuckMs = 0;
    int unstuckCooldownMs = 0;
    int stuckCheckX = Integer.MIN_VALUE;
    int stuckCheckY = Integer.MIN_VALUE;
    int airStuckTicks = 0;
    int airStuckX = Integer.MIN_VALUE;
    int airStuckY = Integer.MIN_VALUE;
    boolean movementBroadcastValid = false;
    int lastBroadcastX = 0;
    int lastBroadcastY = 0;
    int lastBroadcastVelX = 0;
    int lastBroadcastVelY = 0;
    int lastBroadcastStance = 0;
    int lastBroadcastFh = 0;
    int lastGroundFhId = 0;

    BotMovementState(Character bot, Character owner) {
        this.bot = bot;
        this.owner = owner;
    }
}
