[general]
;IME 修复方案，只有0和1两种，优先尝试方案1（更完美），如果会卡门再尝试方案0
imeType=1
;分辨率 (推荐值: 1280x720, 1366x768; 其他可选: 1600x900, 1920x1080, 1024x768; 不保证可用: 800x600)
width=800
height=600
;服务器地址
ServerIP_Address=10.90.194.199
serverIP_Port=8484
;右下角消息数量
MsgAmount=10
;does your UI.wz include the MapleEzorsiaV2wzfiles.img? (true/false, default true if using UI.wz provided in setup guide)
EzorsiaV2WzIncluded=true
;is a resolution specific login frame being used in UI.wz? (true/false, default true if EzorsiaV2WzIncluded=true)
;somewhat obselete, mostly kept for ppl who wanna use their own login frame by directly editing the original frame in wz
CustomLoginFrame=true
;开启后登录界面的UI会按大边框布局，请确保UI使用了大边框才开启
bigLoginFrame=true
;窗口模式
WindowedMode=true
;跳过开头的动画
RemoveLogos=true
;Should VirtuProtect be enabled? (true/false, default true) (this is necessary for clients without CRC bypass such as hendi's clients
;that havent been editted further, can be turned off for clients with CRC bypass to save whatever processing power it uses)
UseVirtuProtect=true
;修复在wine中运行时选角色闪退的问题（副作用是服务器无法获取客户端正确的MAC地址）
fixWine=true;

[optional]
;一种超级机制，不开启的话，升级属性点/技能点会停顿1秒，宠物捡取时攻击会停下来
useTubi=true
; 弓标不挥拳
closeRangeShooting=true
; 自由分配技能点
freeSPAllocation=true
; 攻击不停
nonStopAttack=true
; 对话框文字速显
instantTextDisplay=true
;移速上限
speedMovementCap=180
;跳跃上限
jumpCap=120
[debug]
debug=false